<?php

namespace Database\Seeders;

use App\Imports\DataInfoImport;
use App\Models\Data;
use App\Models\DataConnection;
use App\Models\DataItem;
use App\Models\System;
use Carbon\Carbon;
use DateInterval;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Str;
use Maatwebsite\Excel\Facades\Excel;
use PhpOffice\PhpSpreadsheet\Shared\Date;

class DataTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $collection = $this->listConnections();

        $allSystems = System::all()->collect();

        foreach ($collection as $key => $value) {
            $from = $allSystems->where('name', Arr::get($value, 'from'))->first();
            $to = $allSystems->where('name', Arr::get($value, 'to'))->first();
            if (!$from || !$to) {
                continue;
            }
            $data_code = Arr::get($value, 'data_code');
            $timeAt = Arr::get($value, 'time_at');
            if ($data_code && in_array($data_code, ['ICL_1010', 'ICL_1011']) && App::environment('staging')) {
                $timeAt = Carbon::parse(Carbon::now()->format('Y-m-d') . ' ' . Arr::get($value, 'time_at'))->addHour()->format('H:i');
            }

            $IsUpdate = Arr::get($value, 'is_update');


            $dataconnectData = [
                "name" => Arr::get($value, 'name'),
                "from" => $from->id,
                "to" => $to->id,
                "type" => Arr::get($value, 'type'),
                "frequency" => Arr::get($value, 'frequency'),
                "date_on" => Arr::get($value, 'date_on'),
                "week_on" => Arr::get($value, 'week_on'),
                "time_at" => $timeAt,
                "frequency_between" => Arr::get($value, 'frequency_between'),
                "connection_frequency" => Arr::get($value, 'connection_frequency'),
                "connection_timing" => Arr::get($value, 'connection_timing'),
                "service_class_name" => Arr::get($value, 'service_class_name'),
                "remark" => Arr::get($value, 'remark'),
                "is_import" => Arr::get($value, 'is_import'),
                "import_to_table" => Arr::get($value, 'import_to_table'),
                "file_name_map" => Arr::get($value, 'file_name_map'),
                "data_code" => Arr::get($value, 'data_code'),
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ];
            $dataConnect = DataConnection::withTrashed()
                ->where(DataConnection::DATA_CODE, Arr::get($value, 'data_code'))
                ->first();
            if ($dataConnect) {
                if ($dataConnect->frequency && $dataConnect->frequency == 'any') {
                    unset($dataconnectData['frequency']);
                }
                $dataConnect->update($dataconnectData);
                $dataConnect->syncRoles(Arr::get($value, 'roles'));
            } else {
                $dataConnect = DataConnection::create($dataconnectData);
                $dataConnect->syncRoles(Arr::get($value, 'roles'));
            }
        }
    }

    private function listConnections()
    {
        return [
            [
                "name" => "労働契約データ",
                "from" => "人事奉行",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "03:00",
                "frequency_between" => null,
                "connection_timing" => "03:00",
                "file_name_map" => "roumu-keiyaku.csv",
                "data_code" => "ICL_1000",
                "service_class_name" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => "RPAで取得",
                "is_update" => null,
                "roles" => [ROLE_PERSONNEL_LABOR, ROLE_DX_MANAGER],
            ],
            [
                "name" => "職種データ",
                "from" => "人事奉行",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "03:00",
                "frequency_between" => null,
                "connection_timing" => "03:00",
                "file_name_map" => "shokusyu.csv",
                "data_code" => "ICL_1001",
                "service_class_name" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => "RPAで取得",
                "is_update" => null,
                "roles" => [ROLE_PERSONNEL_LABOR, ROLE_DX_MANAGER],
            ],
            [
                "name" => "資格等級データ",
                "from" => "人事奉行",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "03:00",
                "frequency_between" => null,
                "connection_timing" => "03:00",
                "file_name_map" => "shikaku-tokyu.csv",
                "data_code" => "ICL_1002",
                "service_class_name" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => "RPAで取得",
                "is_update" => null,
                "roles" => [ROLE_PERSONNEL_LABOR, ROLE_DX_MANAGER],
            ],
            [
                "name" => "組織部門データ",
                "from" => "人事奉行",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "03:00",
                "frequency_between" => null,
                "connection_timing" => "03:00",
                "file_name_map" => "soshiki-bumon.csv",
                "data_code" => "ICL_1003",
                "service_class_name" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => "RPAで取得",
                "roles" => [ROLE_PERSONNEL_LABOR, ROLE_DX_MANAGER],
            ],
            [
                "name" => "組織体系データ",
                "from" => "人事奉行",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "03:00",
                "frequency_between" => null,
                "file_name_map" => "soshiki-taikei.csv",
                "connection_timing" => "03:00",
                "data_code" => "ICL_1004",
                "service_class_name" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => "RPAで取得",
                "is_update" => null,
                "roles" => [ROLE_PERSONNEL_LABOR, ROLE_DX_MANAGER],
            ],
            [
                "name" => "組織改編情報データ",
                "from" => "人事奉行",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "03:00",
                "frequency_between" => null,
                "file_name_map" => "soshiki-kaihen.csv",
                "connection_timing" => "03:00",
                "data_code" => "ICL_1005",
                "service_class_name" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => "RPAで取得",
                "is_update" => null,
                "roles" => [ROLE_PERSONNEL_LABOR, ROLE_DX_MANAGER],
            ],
            [
                "name" => "社員データ",
                "from" => "人事奉行",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "03:00",
                "frequency_between" => null,
                "file_name_map" => "shain.csv",
                "connection_timing" => "03:00",
                "data_code" => "ICL_1006",
                "service_class_name" => null,
                "is_import" => 0,
                "import_to_table" => "App\Models\Employee",
                "remark" => "RPAで取得",
                "is_update" => null,
                "roles" => [ROLE_PERSONNEL_LABOR, ROLE_DX_MANAGER],
            ],
            [
                "name" => "考課マスタ体系データ",
                "from" => "人事奉行",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "03:00",
                "frequency_between" => null,
                "file_name_map" => "kouka-master-taikei.csv",
                "connection_timing" => "03:00",
                "data_code" => "ICL_1007",
                "service_class_name" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => "RPAで取得",
                "roles" => [ROLE_PERSONNEL_LABOR, ROLE_DX_MANAGER],
            ],
            [
                "name" => "考課マスタ項目データ",
                "from" => "人事奉行",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "03:00",
                "frequency_between" => null,
                "file_name_map" => "kouka-master-koumoku.csv",
                "connection_timing" => "03:00",
                "data_code" => "ICL_1008",
                "service_class_name" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => "RPAで取得",
                "is_update" => null,
                "roles" => [ROLE_PERSONNEL_LABOR, ROLE_DX_MANAGER],
            ],
            [
                "name" => "給与明細データ",
                "from" => "給与奉行",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => "月次",
                "frequency" => "monthlyOn",
                "date_on" => "17日",
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "file_name_map" => "pay-slip.csv,tax-finalization.csv",
                "connection_timing" => "17日/00:00",
                "data_code" => "ICL_1009",
                "service_class_name" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => "手動でインポート",
                "is_update" => null,
                "roles" => [ROLE_DX_MANAGER],
            ],
            [
                "name" => "アルコールチェックデータ",
                "from" => "IT点呼キーパー",
                "to" => "イズミクラウド",
                "type" => "active",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "04:00",
                "frequency_between" => null,
                "file_name_map" => null,
                "connection_timing" => "04:00",
                "data_code" => "ICL_1010",
                "service_class_name" => "Repository\AlcoholServiceRepository@AlcGetByScrapingAndMailer",
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => "スクレイピングで取得",
                "is_update" => null,
                "roles" => [ROLE_ACCOUNTING, ROLE_PERSONNEL_LABOR, ROLE_DIRECTOR, ROLE_DX_USER, ROLE_DX_MANAGER],
            ],
            [
                "name" => "社員データ・アルコールチェックデータ",
                "from" => "イズミクラウド",
                "to" => "シフト表・タイムシート",
                "type" => "active",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "04:30",
                "frequency_between" => null,
                "file_name_map" => null,
                "connection_timing" => "04:30",
                "data_code" => "ICL_1011",
                "service_class_name" => "Repository\AlcoholServiceRepository@AlcCloudToTimeSheet",
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_ACCOUNTING, ROLE_PERSONNEL_LABOR, ROLE_DIRECTOR, ROLE_DX_USER, ROLE_DX_MANAGER],
            ],
            [
                "name" => "車両台帳",
                "from" => "CSV",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => null,
                "frequency" => "any",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "file_name_map" => "vehicle-list.csv",
                "connection_timing" => "",
                "data_code" => "ICL_1012",
                "service_class_name" => null,
                "is_import" => 1,
                "import_to_table" => null,
                "remark" => "手動でインポート",
                "is_update" => null,
                "roles" => [ROLE_ACCOUNTING, ROLE_GENERAL_AFFAIR, ROLE_PERSONNEL_LABOR, ROLE_DIRECTOR, ROLE_DX_MANAGER],
            ],
            [
                "name" => "メンテナンスリースデータ",
                "from" => "CSV",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => null,
                "frequency" => "any",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "connection_timing" => "",
                "file_name_map" => "maintenance-lease-data.csv",
                "data_code" => "ICL_1013",
                "service_class_name" => null,
                "is_import" => 1,
                "import_to_table" => null,
                "remark" => "手動でインポート",
                "is_update" => null,
                "roles" => [ROLE_ACCOUNTING, ROLE_GENERAL_AFFAIR, ROLE_PERSONNEL_LABOR, ROLE_DIRECTOR, ROLE_DX_MANAGER],
            ],
            [
                "name" => "車両データ",
                "from" => "イズミクラウド",
                "to" => "整備データシステム",
                "type" => "active",
                "connection_frequency" => "月次",
                "frequency" => "monthlyOn",
                "date_on" => "1日",
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "file_name_map" => null,
                "connection_timing" => "1日/00:00",
                "data_code" => "ICL_1014",
                "service_class_name" => "Repository\MaintenanceServiceRepository@SendMaintenanceVehicleData",
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_ACCOUNTING, ROLE_GENERAL_AFFAIR, ROLE_PERSONNEL_LABOR, ROLE_DIRECTOR, ROLE_DX_MANAGER],
            ],
            [
                "name" => "整備実績データ",
                "from" => "整備データシステム",
                "to" => "イズミクラウド",
                "type" => "active",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "connection_timing" => "00:00",
                "file_name_map" => null,
                "data_code" => "ICL_1015",
                "service_class_name" => "Repository\MaintenanceServiceRepository@GetMaintenanceVehicleData",
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_ACCOUNTING, ROLE_GENERAL_AFFAIR, ROLE_PERSONNEL_LABOR, ROLE_DIRECTOR, ROLE_DX_USER, ROLE_DX_MANAGER],
            ],
            [
                "name" => "資産明細",
                "from" => "魔法陣",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => "週次",
                "frequency" => "weeklyOn",
                "date_on" => null,
                "week_on" => 7,
                "time_at" => "10:00",
                "frequency_between" => null,
                "connection_timing" => "日/10:00",
                "file_name_map" => "資産明細.csv",
                "data_code" => "ICL_1016",
                "service_class_name" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => "RPAで取得",
                "is_update" => null,
                "roles" => [ROLE_ACCOUNTING, ROLE_GENERAL_AFFAIR, ROLE_DIRECTOR, ROLE_DX_USER, ROLE_DX_MANAGER],
            ],
            [
                "name" => "社員データ ",
                "from" => "イズミクラウド",
                "to" => "給与明細クラウド",
                "type" => "active",
                "connection_frequency" => "月次",
                "frequency" => "monthlyOn",
                "date_on" => "18日",
                "week_on" => null,
                "time_at" => "02:00",
                "frequency_between" => null,
                "connection_timing" => "18日/02:00",
                "file_name_map" => null,
                "data_code" => "ICL_1017",
                "service_class_name" => "Repository\PayslipServiceRepository@SendPayslipShainData",
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_PERSONNEL_LABOR, ROLE_DX_MANAGER],
            ],
            [
                "name" => "コースマスタ",
                "from" => "イズミクラウド",
                "to" => "シフト表・タイムシート",
                "type" => "active",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "02:30",
                "frequency_between" => null,
                "connection_timing" => "02:30",
                "file_name_map" => null,
                "data_code" => "ICL_1018",
                "service_class_name" => "Repository\CourseRepository@sendCourseDataToTimeSheet",
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_ACCOUNTING, ROLE_GENERAL_AFFAIR, ROLE_PERSONNEL_LABOR, ROLE_DIRECTOR, ROLE_DX_USER, ROLE_DX_MANAGER],
            ],
            [
                "name" => "配送不要日データ",
                "from" => "イズミクラウド",
                "to" => "シフト表・タイムシート",
                "type" => "passive",
                "connection_frequency" => null,
                "frequency" => "any",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "connection_timing" => "",
                "file_name_map" => null,
                "data_code" => "ICL_1019",
                "service_class_name" => "Repository\CourseRepository@sendNonDeliveryToTimeSheet",
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => "手動でインポート",
                "is_update" => null,
                "roles" => [ROLE_ACCOUNTING, ROLE_GENERAL_AFFAIR, ROLE_PERSONNEL_LABOR, ROLE_DIRECTOR, ROLE_DX_USER, ROLE_DX_MANAGER],
            ],
            [
                "name" => "給与データ",
                "from" => "イズミクラウド",
                "to" => "給与明細クラウド",
                "type" => "active",
                "connection_frequency" => "月次",
                "frequency" => "monthlyOn",
                "date_on" => "17日",
                "week_on" => null,
                "time_at" => "12:00",
                "frequency_between" => null,
                "connection_timing" => "17日/12:00",
                "file_name_map" => null,
                "data_code" => "ICL_1020",
                "service_class_name" => "Repository\PayslipServiceRepository@sendPaymentData",
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_DX_MANAGER],
            ],
            [
                "name" => "自賠責データ",
                "from" => "Exeファイル",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "connection_timing" => "00:00",
                "file_name_map" => null,
                "data_code" => "ICL_1021",
                "service_class_name" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_DIRECTOR, ROLE_DX_USER, ROLE_DX_MANAGER],
            ],
            [
                "name" => "車検証データ",
                "from" => "Exeファイル",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "connection_timing" => "00:00",
                "file_name_map" => null,
                "data_code" => "ICL_1022",
                "service_class_name" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_DIRECTOR, ROLE_DX_USER, ROLE_DX_MANAGER],
            ],
            [
                "name" => "車両データ",
                "from" => "イズミクラウド",
                "to" => "ITP",
                "type" => "active",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "23:00",
                "frequency_between" => null,
                "connection_timing" => "23:00",
                "file_name_map" => null,
                "data_code" => "ICL_1023",
                "service_class_name" => "Repository\VehicleServiceRepository@uploadVehicleDataToItp",
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_DIRECTOR, ROLE_DX_USER, ROLE_DX_MANAGER],
            ],
            [
                "name" => "スマホ端末データ",
                "from" => "CLOMO",
                "to" => "イズミクラウド",
                "type" => "active",
                "connection_frequency" => "週次",
                "frequency" => "weeklyOn",
                "date_on" => null,
                "week_on" => 7,
                "time_at" => "05:00",
                "frequency_between" => null,
                "connection_timing" => "日/05:00",
                "file_name_map" => null,
                "data_code" => "ICL_1024",
                "service_class_name" => "Repository\EmployeeServiceRepository@scrapeClomo",
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_DX_MANAGER],
            ],
            [
                "name" => "車両経費データ",
                "from" => "Excel",
                "to" => "イズミクラウド",
                "type" => "passive",
                "connection_frequency" => null,
                "frequency" => "any",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "connection_timing" => "",
                "file_name_map" => null,
                "data_code" => "ICL_1025",
                "service_class_name" => null,
                "is_import" => 1,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_DX_MANAGER],
            ],
            [
                "name" => "損益計算データ",
                "from" => "シフト表・タイムシート",
                "to" => "イズミクラウド",
                "type" => "active",
                "connection_frequency" => null,
                "frequency" => "any",
                "date_on" => "15日",
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "connection_timing" => "",
                "file_name_map" => null,
                "data_code" => "ICL_1026",
                "service_class_name" => "Repository\EmployeeServiceRepository@saveTimeSheetToTable",
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_DX_MANAGER],
            ],
            [
                "name" => "損益計算データ",
                "from" => "PCA",
                "to" => "イズミクラウド",
                "type" => "active",
                "connection_frequency" => null,
                "frequency" => "any",
                "date_on" => null,
                "week_on" => null,
                "time_at" => null,
                "frequency_between" => null,
                "file_name_map" => null,
                "data_code" => "ICL_1027",
                "service_class_name" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_DX_MANAGER],
            ],
            [
                "name" => "損益計算データ",
                "from" => "ITP",
                "to" => "イズミクラウド",
                "type" => "active",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "connection_timing" => "00:00",
                "file_name_map" => null,
                "data_code" => "ICL_1028",
                "service_class_name" => "Repository\VehicleServiceRepository@downloadVehicleDataItp",
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_DX_MANAGER],
            ],
            [
                "name" => "アルコールチェックデータ(バックアップ)/ ALC(Backup)",
                "from" => "IT点呼キーパー(Gmail)",
                "to" => "イズミクラウド",
                "type" => "active",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "05:30",
                "frequency_between" => null,
                "connection_timing" => "05:30",
                "service_class_name" => "Repository\AlcoholServiceRepository@AlcGetByGmail",
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => "スクレイピングで取得",
                "file_name_map" => null,
                "data_code" => "ICL_1029",
                "is_update" => null,
                "roles" => [ROLE_DX_MANAGER],
            ],
            [
                "name" => "本社用打刻データ",
                "from" => "King of Time",
                "to" => "イズミクラウド",
                "type" => "active",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "connection_frequency" => "日次",
                "connection_timing" => "00:00",
                "service_class_name" => "Repository\KingOfTimeServiceRepository@AlcGetEmployeeKingOfTime",
                "remark" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "file_name_map" => null,
                "data_code" => "ICL_1030",
                "is_update" => null,
                "roles" => [ROLE_DX_MANAGER],
            ],
            [
                "name" => "本社用打刻データ",
                "from" => "イズミクラウド",
                "to" => "シフト表・タイムシート",
                "type" => "active",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "connection_frequency" => "日次",
                "connection_timing" => "00:00",
                "service_class_name" => "Repository\KingOfTimeServiceRepository@sendDataKingOfTimeToTimesheet",
                "remark" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "file_name_map" => null,
                "data_code" => "ICL_1031",
                "is_update" => null,
                "roles" => [ROLE_DX_MANAGER],
            ],
            [
                "name" => "採用データ",
                "from" => "外部採用システム",
                "to" => "イズミクラウド",
                "type" => "active",
                "frequency" => "any",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "connection_frequency" => "時次",
                "connection_timing" => "",
                "service_class_name" => "Repository\VehicleServiceRepository@downloadVehicleDataItp",
                "remark" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "file_name_map" => null,
                "data_code" => "ICL_1032",
                "is_update" => null,
                "roles" => [ROLE_DX_MANAGER],
            ],
            [
                "name" => "採用データ",
                "from" => "イズミクラウド",
                "to" => "イズミワークス",
                "type" => "active",
                "frequency" => "any",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "00:00",
                "frequency_between" => null,
                "connection_frequency" => "時次",
                "connection_timing" => "",
                "service_class_name" => "Repository\VehicleServiceRepository@downloadVehicleDataItp",
                "remark" => null,
                "is_import" => 0,
                "import_to_table" => null,
                "file_name_map" => null,
                "data_code" => "ICL_1033",
                "is_update" => null,
                "roles" => [ROLE_DX_MANAGER],
            ],
            [
                "name" => "テレニシALC / ALC",
                "from" => "IT点呼キーパー",
                "to" => "イズミクラウド",
                "type" => "active",
                "connection_frequency" => "日次",
                "frequency" => "dailyAt",
                "date_on" => null,
                "week_on" => null,
                "time_at" => "04:00",
                "frequency_between" => null,
                "connection_timing" => "04:00",
                "file_name_map" => null,
                "data_code" => "ICL_1034",
                "service_class_name" => "Repository\ItKeeperServiceRepository@AlcV2GetByApi",
                "is_import" => 0,
                "import_to_table" => null,
                "remark" => null,
                "is_update" => null,
                "roles" => [ROLE_DX_MANAGER],
            ]
        ];
    }
}
