import Layout from '@/layout';
import CONST_ROLE from '@/const/role';

const masterManager = {
    path: '/master-manager',
    name: 'MasterManager',
    meta: {
        title: 'ROUTER_USER_MANAGEMENT',
        icon: 'fas fa-cog',
        roles: [
            CONST_ROLE.CREW,
            CONST_ROLE.CLERKS,
            CONST_ROLE.TL,
            CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
            CONST_ROLE.PERSONNEL_LABOR,
            CONST_ROLE.GENERAL_AFFAIRS,
            CONST_ROLE.ACCOUNTING,
            CONST_ROLE.AM_SM,
            CONST_ROLE.QUALITY_CONTROL,
            CONST_ROLE.SALES,
            CONST_ROLE.SITE_MANAGER,
            CONST_ROLE.HQ_MANAGER,
            CONST_ROLE.DEPARTMENT_MANAGER,
            CONST_ROLE.EXECUTIVE_OFFICER,
            CONST_ROLE.DIRECTOR,
            CONST_ROLE.DX_USER,
            CONST_ROLE.DX_MANAGER,
        ],
    },
    component: Layout,
    children: [
        {
            path: 'employee-master',
            name: 'EmployeeMaster',
            meta: {
                title: 'ROUTER_EMPLOYEE_MASTER',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.PERSONNEL_LABOR,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: false,
            component: () => import(/* webpackChunkName: "Employee Master" */ '@/pages/EmployeeMaster/index.vue'),
        },
        {
            path: 'employee-master-detail/:id',
            name: 'EmployeeMasterDetail',
            meta: {
                title: 'ROUTER_EMPLOYEE_MASTER',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.PERSONNEL_LABOR,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Employee Master Detail" */ '@/pages/EmployeeMaster/detail.vue'),
        },
        {
            path: 'employee-master-document/:id',
            name: 'EmployeeMasterDocument',
            meta: {
                title: 'ROUTER_EMPLOYEE_DOCUMENT',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.PERSONNEL_LABOR,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Employee Master Detail" */ '@/pages/EmployeeMaster/document.vue'),
        },
        {
            path: 'employee-master-upload',
            name: 'EmployeeMasterUploadPDF',
            meta: {
                title: 'ROUTER_EMPLOYEE_DOCUMENT',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.PERSONNEL_LABOR,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Employee Master Upload" */ '@/pages/EmployeeMaster/upload.vue'),
        },
        {
            path: 'employee-master-edit/:id',
            name: 'EmployeeMasterEdit',
            meta: {
                title: 'ROUTER_EMPLOYEE_MASTER',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.PERSONNEL_LABOR,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Employee Master Edit" */ '@/pages/EmployeeMaster/edit.vue'),
        },
        {
            path: 'course-master',
            name: 'CourseMaster',
            meta: {
                title: 'ROUTER_COURSE_MASTER',
                roles: [
                    CONST_ROLE.CREW,
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.ACCOUNTING,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SALES,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: false,
            component: () => import(/* webpackChunkName: "Course Master" */ '@/pages/CourseMaster/index.vue'),
        },
        {
            path: 'course-master-create',
            name: 'CourseMasterCreate',
            meta: {
                title: 'ROUTER_COURSE_MASTER',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Course Master Create" */ '@/pages/CourseMaster/create.vue'),
        },
        {
            path: 'course-master-detail/:id',
            name: 'CourseMasterDetail',
            meta: {
                title: 'ROUTER_COURSE_MASTER',
                roles: [
                    CONST_ROLE.CREW,
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.ACCOUNTING,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SALES,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Course Master Detail" */ '@/pages/CourseMaster/detail.vue'),
        },
        {
            path: 'course-master-edit/:id',
            name: 'CourseMasterEdit',
            meta: {
                title: 'ROUTER_COURSE_MASTER',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Course Master Edit" */ '@/pages/CourseMaster/edit.vue'),
        },
        {
            path: 'route-master',
            name: 'ROUTER_ROUTE_MASTER',
            meta: {
                title: 'ROUTER_ROUTE_MASTER',
                roles: [
                    CONST_ROLE.CREW,
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.ACCOUNTING,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SALES,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: false,
            component: () => import(/* webpackChunkName: "Route Master" */ '@/pages/RouteMaster/index.vue'),
        },
        {
            path: 'route-master-create',
            name: 'RouteMasterCreate',
            meta: {
                title: 'ROUTER_ROUTE_MASTER',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Route Master Create" */ '@/pages/RouteMaster/create.vue'),
        },
        {
            path: 'route-master-edit/:id',
            name: 'RouteMasterEdit',
            meta: {
                title: 'ROUTER_ROUTE_MASTER',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Route Master Edit" */ '@/pages/RouteMaster/edit.vue'),
        },
        {
            path: 'store-master',
            name: 'StoreMaster',
            meta: {
                title: 'ROUTER_STORE_MASTER',
                roles: [
                    CONST_ROLE.CREW,
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SALES,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: false,
            component: () => import(/* webpackChunkName: "Store Master" */ '@/pages/StoreMaster/index.vue'),
        },
        {
            path: 'store-master-create',
            name: 'StoreMasterCreate',
            meta: {
                title: 'ROUTER_STORE_MASTER',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Store Master Create" */ '@/pages/StoreMaster/create.vue'),
        },
        {
            path: 'store-master-detail/:id',
            name: 'StoreMasterDetail',
            meta: {
                title: 'ROUTER_STORE_MASTER',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Store Master Detail" */ '@/pages/StoreMaster/detail.vue'),
        },
        {
            path: 'store-master-edit/:id',
            name: 'StoreMasterEdit',
            meta: {
                title: 'ROUTER_STORE_MASTER',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Store Master Edit" */ '@/pages/StoreMaster/edit.vue'),
        },
        {
            path: 'customer-master',
            name: 'CustomerMaster',
            meta: {
                title: 'ROUTER_CUSTOMER_MASTER',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.PERSONNEL_LABOR,
                    CONST_ROLE.GENERAL_AFFAIRS,
                    CONST_ROLE.ACCOUNTING,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SALES,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: false,
            component: () => import(/* webpackChunkName: "Customer Master" */ '@/pages/CustomerMaster/index.vue'),
        },
        {
            path: 'customer-master-create',
            name: 'CustomerMasterCreate',
            meta: {
                title: 'ROUTER_CUSTOMER_MASTER',
                roles: [
                    CONST_ROLE.ACCOUNTING,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Customer Master Create" */ '@/pages/CustomerMaster/create.vue'),
        },
        {
            path: 'customer-master-edit/:id',
            name: 'CustomerMasterEdit',
            meta: {
                title: 'ROUTER_CUSTOMER_MASTER',
                roles: [
                    CONST_ROLE.ACCOUNTING,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Customer Master Edit" */ '@/pages/CustomerMaster/edit.vue'),
        },
        {
            path: 'vehicle-master',
            name: 'VehicleMasterList',
            meta: {
                title: 'ROUTER_VEHICLE_MASTER',
                roles: [
                    CONST_ROLE.CREW,
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.PERSONNEL_LABOR,
                    CONST_ROLE.GENERAL_AFFAIRS,
                    CONST_ROLE.ACCOUNTING,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SALES,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: false,
            component: () => import(/* webpackChunkName: "Vehicle Master List" */ '@/pages/VehicleMaster/index.vue'),
        },
        {
            path: 'vehicle-master/create',
            name: 'VehicleMasterCreate',
            meta: {
                title: 'ROUTER_VEHICLE_MASTER',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.GENERAL_AFFAIRS,
                    CONST_ROLE.ACCOUNTING,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Vehicle Master Create" */ '@/pages/VehicleMaster/create.vue'),
        },
        {
            path: 'vehicle-master/detail/:id',
            name: 'VehicleMasterDetail',
            meta: {
                title: 'ROUTER_VEHICLE_MASTER',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.GENERAL_AFFAIRS,
                    CONST_ROLE.ACCOUNTING,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SALES,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Vehicle Master Detail" */ '@/pages/VehicleMaster/detail.vue'),
        },
        {
            path: 'vehicle-master/edit/:id',
            name: 'VehicleMasterEdit',
            meta: {
                title: 'ROUTER_VEHICLE_MASTER',
                roles: [
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.GENERAL_AFFAIRS,
                    CONST_ROLE.ACCOUNTING,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Vehicle Master Edit" */ '@/pages/VehicleMaster/edit.vue'),
        },
        {
            path: 'insurance-rate-master',
            name: 'InsuranceRateMasterIndex',
            meta: {
                title: 'INSURANCE_RATE_MASTER',
                roles: [
                    CONST_ROLE.CREW,
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.ACCOUNTING,
                    CONST_ROLE.GENERAL_AFFAIRS,
                    CONST_ROLE.PERSONNEL_LABOR,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: false,
            component: () => import(/* webpackChunkName: "Insurance Rate Master Index" */ '@/pages/InsuranceRateMaster/index.vue'),
        },
        {
            path: 'insurance-rate-master/edit/:id',
            name: 'InsuranceRateMasterEdit',
            meta: {
                title: 'INSURANCE_RATE_MASTER',
                roles: [
                    CONST_ROLE.CREW,
                    CONST_ROLE.CLERKS,
                    CONST_ROLE.TL,
                    CONST_ROLE.DEPARTMENT_OFFICE_STAFF,
                    CONST_ROLE.ACCOUNTING,
                    CONST_ROLE.GENERAL_AFFAIRS,
                    CONST_ROLE.PERSONNEL_LABOR,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "Insurance Rate Master Edit" */ '@/pages/InsuranceRateMaster/edit.vue'),
        },
        {
            path: 'user-master',
            name: 'UserMaster',
            meta: {
                title: 'ROUTER_USER_MASTER',
                roles: [
                    CONST_ROLE.PERSONNEL_LABOR,
                    CONST_ROLE.AM_SM,
                    CONST_ROLE.QUALITY_CONTROL,
                    CONST_ROLE.SITE_MANAGER,
                    CONST_ROLE.HQ_MANAGER,
                    CONST_ROLE.DEPARTMENT_MANAGER,
                    CONST_ROLE.EXECUTIVE_OFFICER,
                    CONST_ROLE.DIRECTOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: false,
            component: () => import(/* webpackChunkName: "User Master List" */ '@/pages/UserManagement/List.vue'),
        },
        {
            path: 'user-master-create',
            name: 'UserMasterCreate',
            meta: {
                title: 'ROUTER_USER_MASTER',
                roles: [],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "User Master Create" */ '@/pages/UserManagement/Create.vue'),
        },
        {
            path: 'user-master-detail/:id',
            name: 'UserMasterDetail',
            meta: {
                title: 'ROUTER_USER_MANAGEMENT_PAGE_DETAIL',
                roles: [
                    CONST_ROLE.PERSONNEL_LABOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "User Master Detail" */ '@/pages/UserManagement/Detail.vue'),
        },
        {
            path: 'user-master-edit/:id',
            name: 'UserMasterEdit',
            meta: {
                title: 'ROUTER_USER_MASTER',
                roles: [
                    CONST_ROLE.PERSONNEL_LABOR,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "User Master Edit" */ '@/pages/UserManagement/Edit.vue'),
        },
        {
            path: 'department-master/index',
            name: 'DepartmentMasterIndex',
            meta: {
                title: 'ROUTER_DEPARTMENT',
            },
            hidden: false,
            component: () => import(/* webpackChunkName: "DepartmentMasterIndex" */ '@/pages/DepartmentMaster/index.vue'),
        },
        {
            path: 'department-master/edit/:id',
            name: 'DepartmentMasterEdit',
            meta: {
                title: 'ROUTER_DEPARTMENT',
            },
            hidden: true,
            component: () => import(/* webpackChunkName: "DepartmentMaterEdit" */ '@/pages/DepartmentMaster/edit.vue'),
        },
        {
            path: 'urgent-contact/index',
            name: 'UrgentContactIndex',
            meta: {
                title: 'ROUTER_URGENT_CONTACT',
                roles: [
                    CONST_ROLE.PERSONNEL_LABOR,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: false,
            component: () => import(/* webpackChunkName: "UrgentContactIndex" */ '@/pages/UrgentContact/index.vue'),
        },
        {
            path: 'pocket-book',
            name: 'PocketBook',
            meta: {
                title: 'ROUTER_POKET_BOOK',
                roles: [
                    CONST_ROLE.GENERAL_AFFAIRS,
                    CONST_ROLE.DX_USER,
                    CONST_ROLE.DX_MANAGER,
                ],
            },
            hidden: false,
            component: () => import(/* webpackChunkName: "User Master List" */ '@/pages/PocketBook/List.vue'),
        },
    ],
};

export default masterManager;
